version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: farmstore-dev:latest
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - data:/usr/src/app/data
      - uploads:/usr/src/app/uploads
    restart: unless-stopped

volumes:
  data:
  uploads:
