services:
  - type: web
    name: farm-technology-api-sparsh
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
