import React, { useState } from 'react';
import { api } from '../lib/api';
import './Contact.css';

const initialForm = { name: '', email: '', phone: '', subject: '', message: '' };

export default function Contact() {
  const [formData, setFormData] = useState(initialForm);
  const [status, setStatus] = useState('idle');
  const [message, setMessage] = useState('');
  const handleChange = (event) => setFormData((previous) => ({ ...previous, [event.target.name]: event.target.value }));
  const handleSubmit = async (event) => { event.preventDefault(); setStatus('loading'); setMessage(''); try { await api.contact(formData); setStatus('success'); setMessage('Your message is with the Farm Technology team. We will get back to you soon.'); setFormData(initialForm); } catch (error) { setStatus('error'); setMessage(error.message || 'Your message could not be sent. Please try again.'); } };
  return <section id="contact" className="contact-section"><div className="container contact-layout"><div className="contact-copy"><p className="eyebrow">FIELD GUIDE / 02</p><h2>Keep the<br /><em>conversation</em> growing.</h2><p>Need product guidance, a catalogue question, or help with your supply list? Send the detail and the team will follow up.</p><div id="field-guide" className="contact-notes"><div><span>01</span><strong>Build a list</strong><small>Search the live catalog and save items in your basket.</small></div><div><span>02</span><strong>Choose your pace</strong><small>Stay a guest or sign in to preserve your list across devices.</small></div><div><span>03</span><strong>Ask the team</strong><small>Use this note for product and store questions.</small></div></div></div><div className="contact-panel"><div className="contact-panel__top"><span>New field note</span><i>⌁</i></div><form className="contact-form" onSubmit={handleSubmit}><div className="form-grid"><label>FULL NAME<input type="text" name="name" value={formData.name} onChange={handleChange} required placeholder="Your name" /></label><label>EMAIL ADDRESS<input type="email" name="email" value={formData.email} onChange={handleChange} required placeholder="you@example.com" /></label></div><div className="form-grid"><label>PHONE <small>optional</small><input type="tel" name="phone" value={formData.phone} onChange={handleChange} placeholder="Your number" /></label><label>SUBJECT<input type="text" name="subject" value={formData.subject} onChange={handleChange} required placeholder="How can we help?" /></label></div><label>YOUR NOTE<textarea name="message" rows="5" value={formData.message} onChange={handleChange} required placeholder="Tell us what you need for the next field task…" /></label>{message && <p className={`form-status form-status--${status}`} role={status === 'error' ? 'alert' : 'status'}>{message}</p>}<button type="submit" className="submit-btn" disabled={status === 'loading'}>{status === 'loading' ? 'Sending note…' : 'Send field note'}<span>→</span></button></form></div></div></section>;
}
