name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Start server
        run: |
          # start the server in background so the next step can use it
          node server.js &
          # wait for server to be available (max ~15s)
          n=0; until curl -sS http://localhost:3000/ > /dev/null || [ $n -ge 15 ]; do n=$((n+1)); sleep 1; done

      - name: Run socket smoke test
        run: node tests/test-socket.js
